#
listen = *
protocols = pop3 imap
auth_mechanisms = plain login
disable_plaintext_auth = no
#log_path = /var/log/dovecot/dovecot.log
#info_log_path = /var/log/dovecot/dovecot.log
#debug_log_path = /var/log/dovecot/dovecot.log
log_path = /data/logs/dovecot.log
#log_path = /dev/stderr
#info_log_path = /dev/stdout
#debug_log_path = /dev/stdout
auth_verbose = yes
auth_verbose_passwords = yes
auth_debug = yes
auth_debug_passwords = yes

first_valid_gid = 8
first_valid_uid = 8
last_valid_gid = 8
last_valid_uid = 8
login_greeting = The Microsoft Exchange service is ready.
log_timestamp = "%Y-%m-%d %H:%M:%S "
mail_gid = mail
#mail_location = mbox:/tmp/dovecot/mail
mail_location = maildir:/data/dovecot/Maildir
mail_privileged_group = mail
mail_uid = mail

passdb {
  args = scheme=plain /data/files/pwd
  driver = passwd-file
}
userdb {
  args = /data/files/pwd
  driver = passwd-file
  default_fields = uid=8 gid=8 home=/data/home
}

ssl = yes
ssl_cert = </etc/dovecot/fullchain.pem
ssl_key = </etc/dovecot/privkey.pem
ssl_prefer_server_ciphers = yes
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS
ssl_dh = </data/common/dh-dovecot.pem
